fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check

products:
    type:     rest
    prefix: /api/v1
    resource: AppBundle:Product

app:
    path: /{any}
    methods: [ 'GET' ]
    requirements: { any: '.*' }
    defaults:
        _controller: AppBundle:App:index
