api_register:
    path: /api/v1/users
    methods: POST
    defaults:
        _controller: AppBundle:User:register

api_login_check:
    path: /api/v1/login

products:
    type:     rest
    prefix: /api/v1
    resource: AppBundle:Product

app:
    path: /{any}
    methods: [ 'GET' ]
    requirements: { any: '.*' }
    defaults:
        _controller: AppBundle:App:index

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
