products:
    type:     rest
    prefix: /api/v1
    resource: AppBundle:Product

app:
    path: /{any}
    methods: [ 'GET' ]
    requirements: { any: '.*' }
    defaults:
        _controller: AppBundle:App:index
